### ISSUE TITLE
Outdated Version Badges

### ISSUE THREAD

**Issue by michael-hawker** [scottkuhl/awesome-winui#1]
Hi! Thanks for this great resource!

I noticed the shield for versioning next to the Windows Community Toolkit was 'V3' but we're on `V6.1`.

Are dots supported? It looks just like a static image reference?

Did we want to do something more with pulling data from NuGet so it updates automatically? E.g. we have this on our readme for the Toolkit: [![NuGet](https://img.shields.io/nuget/v/Microsoft.Toolkit.Uwp.svg)](https://www.nuget.org/profiles/Microsoft.Toolkit)

Thoughts?

**Comment by scottkuhl** [comment]
The V3 badge was meant to be a signal that a version supporting WinUI 3 is available because there is a lot of interest in it.  It was not meant to be the version on the link.  You'll notice the link for the community toolkit is pointing to the WinUI 3 version.

I see that it can be confusing. 

I think what I'll do is change the version number from V3 on those tags to WinUI 3 and add a note to look for that badge for people who are mostly interested in WinUI 3 stuff.  Eventually this badge will just go away.

Also, I'll update the link on the toolkit to point to the main page and a separate link in the description to the WinUI 3 version.

Does that work?

**Comment by michael-hawker** [comment]
@scottkuhl ah, that makes sense, I totally didn't read it as WinUI 3 support. I also didn't see the link went to that issue directly.

Makes sense, thanks!

**Comment by scottkuhl** [comment]
These changes are in this commit:

https://github.com/scottkuhl/awesome-winui/commit/baaa0b472f4c68d0ccde25364f1da0e6eac589b0
